# Generated by Django 3.0.5 on 2021-07-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_auto_20210706_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/CustomerProfilePic/profile.jpg', null=True, upload_to='profile_pic/CustomerProfilePic/'),
        ),
    ]
