# Generated by Django 3.0.5 on 2021-07-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_auto_20210707_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/CustomerProfilePic/profile.jpg', upload_to='profile_pic/CustomerProfilePic/'),
        ),
    ]
